# Generated by Django 5.1.6 on 2025-02-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.SlugField(default='', max_length=128),
        ),
    ]
