# Generated by Django 5.1.6 on 2025-03-08 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_image_alter_post_text_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='deslikes',
            new_name='dislikes',
        ),
    ]
